#!/usr/bin/env python3

if __name__ == "__main__":
    from sys import argv, version_info
    from src.interpreter import Interpreter
    assert version_info >= (3, 10, 12)
    match argv:
        case [program, file]:
            with open(file, encoding="utf-8") as f:
                Interpreter.run_script(f.read())
        case [program]:
            Interpreter.run_repl()
